#!/usr/bin/env bash

# this command reads the markdown folder and creates entries in the Django DB

echo "+++++++++++++++++"
echo -e "\nREFRESHING BLOGS INDEX..."
echo "+++++++++++++++++"
src/manage.py do_blogs_reindex $1


# $ blogs_reindex --help // more info
