#!/usr/bin/env bash

cd src 

python manage.py makemigrations

python manage.py migrate

echo "from django.contrib.auth.models import User; User.objects.create_superuser('mpasin', 'michele.pasin@gmail.com', 'cazzone99')" | python manage.py shell

echo "SUPERUSER CREATED: 'mpasin'"