#!/usr/bin/env bash

echo "================="
echo "Dumping site.."
echo "================="

./tools/dump-site


echo -e "\nCommit and push"
echo "+++++++++++++++++"
git add -A 
git commit -m "live site auto update"
git push

echo -e "\rDone"
echo "+++++++++++++++++"
