#!/usr/bin/env bash

echo "================="
echo "Dumping site.."
echo "================="

./tools/dump-site

echo "================="
echo -e "\nCommit and push"
echo "================="

./tools/publish-site

echo -e "\rDone"
echo "+++++++++++++++++"
