#!/usr/bin/env bash

echo "================="
echo "PREREQUISITE"
echo "Ensure site is running on 127.0.0.1:8000..."
echo "================="


if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null ; then
    echo ">>>>>>> DJANGO is RUNNING! "
    echo "================="
else
    echo "********* Django not running **********"
    echo ".. Exiting process. Please run the django server first."
    exit 1
fi



#
# Folders ignored from build:
# - assets: managed manually for static files 
# - archived: contains legacy content which is unchanged 
#


echo -e "\nCLEAN UP BUILD DIR"
echo "+++++++++++++++++"
rm -rf build/*

echo -e "\nRSYNC /DOCS TO /DOCS-PREV"
echo "+++++++++++++++++"
# the legacy /blog static files don't need to be refreshed
rsync -av --delete --exclude archived --exclude assets docs/ docs-prev/

echo -e "\nGRAB SITE INTO BUILD DIRECTORY" 
echo "+++++++++++++++++"
wget  -P build -mkEpnp -nH http://127.0.0.1:8000/ --wait=0.1 --exclude-domains www.michelepasin.org
# add a log file
cd build
touch "$(date +"%Y_%m_%d_%I_%M_%p").log"
cd ..

echo -e "\RSYNC BUILD DIRECTORY TO /DOCS"
echo "+++++++++++++++++"
rsync -av --delete --exclude '.nojekyll' --exclude 'CNAME' --exclude archived --exclude assets build/ docs/



echo "================="
echo "Dumping data.."
echo "================="

./tools/data-dump



# WGET HOWTO
# https://www.gnu.org/software/wget/manual/wget.html

# -   `--mirror` – Makes (among other things) the download recursive.
# -   `--convert-links` – convert all the links (also to stuff like CSS stylesheets) to relative, so it will be suitable for offline viewing.
# -   `--adjust-extension` – Adds suitable extensions to filenames (`html` or `css`) depending on their content-type.
# -   `--page-requisites` – Download things like CSS style-sheets and images required to properly display the page offline.
# -   `--no-parent` – When recursing do not ascend to the parent directory. It useful for restricting the download to only a portion of the site.
# -  `--no-host-directories` – Disable generation of host-prefixed directories. By default, invoking Wget with ‘-r http://fly.srk.fer.hr/’ will create a structure of directories beginning with fly.srk.fer.hr/. This option disables such behavior.
# -  `--wait` – Waiting time between calls. Set reasonable or random waiting times between two downloads to avoid the Connection closed by peer error.

