# Generated by Django 2.1.3 on 2021-08-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Feel free to use https://html-online.com/editor', null=True, verbose_name='description (html welcome!)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Feel free to use https://html-online.com/editor', null=True, verbose_name='description (html welcome!)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='urlstub',
            field=models.CharField(help_text='No spaces or dashes please', max_length=255, verbose_name='url stub'),
        ),
    ]
