# Generated by Django 2.1.3 on 2022-04-17 17:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myutils.modelextra.myfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researchapp', '0006_auto_20220417_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', myutils.modelextra.myfields.CreationDateTimeField(blank=True, default=datetime.datetime.now, help_text='The time this record was firstly created. Do not modify.', verbose_name='created on date')),
                ('updated_at', myutils.modelextra.myfields.ModificationDateTimeField(blank=True, default=datetime.datetime.now, help_text='Automatically updated each time the record is saved.', verbose_name='modified on date')),
                ('editedrecord', models.BooleanField(default=False, help_text='Tick to indicate that this record has been finalized', verbose_name='edited record?')),
                ('review', models.BooleanField(default=False, help_text='Tick to indicate that this record is under review by the editorial team', verbose_name='review')),
                ('internal_notes', models.TextField(blank=True, verbose_name='internal_notes')),
                ('name', models.CharField(max_length=765)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_blogcategory', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='No need to edit: automatically set when saving', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_blogcategory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog-Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='publications', to='researchapp.BlogCategory', verbose_name='categories'),
        ),
    ]
