# Generated by Django 2.1.3 on 2025-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchapp', '0007_auto_20220417_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='publications', to='researchapp.BlogCategory', verbose_name='Blog categories'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='publications', to='researchapp.Tag', verbose_name='tags (shared with projects)'),
        ),
    ]
